# Generated by Django 5.0.3 on 2024-04-17 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=250)),
                ('movie_type', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('release_date', models.DateField(auto_now=True)),
                ('movie_image', models.ImageField(upload_to='cinima')),
            ],
        ),
    ]
