# Generated by Django 5.0.3 on 2024-04-17 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dummyitems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('place', models.CharField(max_length=250)),
                ('description', models.TextField()),
            ],
        ),
    ]
