# Generated by Django 5.0.3 on 2024-04-08 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_doctors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prdct_name', models.CharField(max_length=255)),
                ('prdct_price', models.CharField(max_length=255)),
                ('prdct_description', models.TextField()),
            ],
        ),
    ]
