# Generated by Django 5.0.3 on 2024-04-12 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='prdct_age',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
