# Generated by Django 5.0.3 on 2024-04-17 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_products_prdct_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='prdct_age',
        ),
    ]
